### ISSUE TITLE
CUDAToolkit not specified in CMakeLists.txt

### ISSUE THREAD

**Issue by MQSchleich** [eth-cscs/COSMA#86]
You do not specify the path to the CUDA libraries. Therefore, one can't install COSMA with CUDA support. 
When running

```bash
cmake -DCOSMA_BLAS=CUDA ..
``` 

Gives

```bash
- Selected BLAS backend for COSMA: CUDA
-- Selected SCALAPACK backend for COSMA: OFF
-- cxxopts version 2.2.0
CUDA not found. Please specify CUDA_PATH variable.
CMake Error at /usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CUBLAS (missing: CUDA_TOOLKIT_INCLUDE CUDA_CUDART_LIB)
Call Stack (most recent call first):
  /usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  libs/Tiled-MM/cmake/FindCUBLAS.cmake:51 (find_package_handle_standard_args)
  libs/Tiled-MM/CMakeLists.txt:30 (find_package)
```

**Comment by kabicm** [comment]
Hi @MQSchleich, did you actually set the variable `CUDA_PATH` to point to your cuda installation?

Can you tell me what you get when you do:
```
echo $CUDA_PATH
ls $CUDA_PATH
```

**Comment by kabicm** [comment]
Just a small clarification: it's the user's responsibility to ensure that the environment variable `CUDA_PATH` is containing the right CUDA installation path. It's usually set up automatically when you install the CUDA drivers. In HPC environments, it's usually automatically set when you load the CUDA modules.

Let me know if you need any help with that.

**Comment by kabicm** [comment]
I will close this issue, since I didn't hear back from you in a while. Feel free to reopen it if you still have the issue.

**Comment by MQSchleich** [comment]
Yes, I am sorry to let you wait. I was quite busy with the project. Yes, indeed there is no $CUDA_PATH set globally. I am working on COLAB, so how do I properly set the CUDA_PATH to work for COSMA installations?

**Comment by kabicm** [comment]
Hi Manuel,

No problem! In COLAB, did you set the hardware acceleration to GPU (https://stackoverflow.com/questions/50560395/how-to-install-cuda-in-google-colab-gpus)?

**Comment by MQSchleich** [comment]
Hey Kabi,

Yes, indeed, CUDA is installed and set. Other libraries e.g. GROMACS or PyTorch link automatically to CUDA.

**Comment by kabicm** [comment]
Hi Manuel, I hope we have fixed this now in the master branch. Can you test if it works for you now?

Make sure to do recursive git clone again, because we also updated the `Tiled-MM` submodule (which is the GPU backend of COSMA).

It would be great if you could test it today, because this version of COSMA might go into the latest CP2K version that should be released tomorrow, so it's good to fix it before.

Thanks!

**Comment by MQSchleich** [comment]
I tested it. However, running

```bash
!mkdir build
%cd build

# set up the compiler, e.g. with:
!export CC=`which cc`
!export CXX=`which CC`

# choose BLAS and SCALAPACK versions you want to use
# COSMA_BLAS can be: MKL, OpenBLAS, CRAY_LIBSCI, CUDA, ROCM, CUSTOM
# COSMA_SCALAPACK can be MKL, CRAY_LIBSCI, CUSTOM
!cmake -DCOSMA_BLAS=CUDA ..
!make -j 4
!make install
```
 
results in

```bash
/usr/bin/ld: cannot find -lCUDA_cublas_device_LIBRARY-NOTFOUND
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test.multiply_using_layout.dir/build.make:96: recipe for target 'tests/test.multiply_using_layout' failed
make[2]: *** [tests/test.multiply_using_layout] Error 1
CMakeFiles/Makefile2:509: recipe for target 'tests/CMakeFiles/test.multiply_using_layout.dir/all' failed
make[1]: *** [tests/CMakeFiles/test.multiply_using_layout.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by kabicm** [comment]
Can you try again the current master version? As @pkestene noticed, we had a typo in the cmake script https://github.com/eth-cscs/COSMA/pull/88 which might have caused it.

Let me know if it works this time.

**Comment by MQSchleich** [comment]
Sure. I ran it this time I get
```bash 
/usr/bin/ld: cannot find -lCUDA_cublas_device_LIBRARY-NOTFOUND
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test.multiply_using_layout.dir/build.make:96: recipe for target 'tests/test.multiply_using_layout' failed
make[2]: *** [tests/test.multiply_using_layout] Error 1
CMakeFiles/Makefile2:509: recipe for target 'tests/CMakeFiles/test.multiply_using_layout.dir/all' failed
make[1]: *** [tests/CMakeFiles/test.multiply_using_layout.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 72%] Linking CXX executable test.mapper
/usr/bin/ld: cannot find -lCUDA_cublas_device_LIBRARY-NOTFOUND
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test.mapper.dir/build.make:96: recipe for target 'tests/test.mapper' failed
make[2]: *** [tests/test.mapper] Error 1
CMakeFiles/Makefile2:628: recipe for target 'tests/CMakeFiles/test.mapper.dir/all' failed
make[1]: *** [tests/CMakeFiles/test.mapper.dir/all] Error 2
[ 73%] Linking CXX executable test.scalar_matmul
/usr/bin/ld: cannot find -lCUDA_cublas_device_LIBRARY-NOTFOUND
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test.scalar_matmul.dir/build.make:96: recipe for target 'tests/test.scalar_matmul' failed
make[2]: *** [tests/test.scalar_matmul] Error 1
CMakeFiles/Makefile2:550: recipe for target 'tests/CMakeFiles/test.scalar_matmul.dir/all' failed
make[1]: *** [tests/CMakeFiles/test.scalar_matmul.dir/all] Error 2
[ 75%] Linking CXX executable test.multiply
/usr/bin/ld: cannot find -lCUDA_cublas_device_LIBRARY-NOTFOUND
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test.multiply.dir/build.make:96: recipe for target 'tests/test.multiply' failed
make[2]: *** [tests/test.multiply] Error 1
CMakeFiles/Makefile2:669: recipe for target 'tests/CMakeFiles/test.multiply.dir/all' failed
make[1]: *** [tests/CMakeFiles/test.multiply.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
[ 10%] Built target Tiled-MM
[ 27%] Built target costa
[ 56%] Built target cosma
[ 60%] Built target gtest
[ 61%] Built target main_gtest_mpi
[ 63%] Linking CXX executable test.multiply_using_layout
/usr/bin/ld: cannot find -lCUDA_cublas_device_LIBRARY-NOTFOUND
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test.multiply_using_layout.dir/build.make:96: recipe for target 'tests/test.multiply_using_layout' failed
make[2]: *** [tests/test.multiply_using_layout] Error 1
CMakeFiles/Makefile2:509: recipe for target 'tests/CMakeFiles/test.multiply_using_layout.dir/all' failed
make[1]: *** [tests/CMakeFiles/test.multiply_using_layout.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by kabicm** [comment]
Thanks for checking! Which version of CMake are you using?

**Comment by MQSchleich** [comment]
You are welcome. The version of Cmake after checking ```cmake --version``` is:
```bash 
cmake version 3.12.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
The complete output of the ```make``` command is: 
```bash 
/content/COSMA/build
-- Setting build type to 'Release' as none was specified.
-- Selected BLAS backend for COSMA: CUDA
-- Selected SCALAPACK backend for COSMA: OFF
-- The BLAS backend that SCALAPACK is linked to: OFF
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- cxxopts version 2.2.0
-- Selected TILEDMM_GPU_BACKEND: CUDA
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "11.0") 
-- Building with no SCALAPACK interface support.
-- Selected ScaLAPACK backend for COSTA: OFF
-- Found MPI: TRUE (found version "3.1") found components:  CXX 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5") found components:  CXX 
CMake Warning at libs/COSTA/CMakeLists.txt:101 (message):
  No ScaLAPACK interface is specified.  Building COSTA without SCALAPACK
  wrappers.


-- CUDA_TOOLKIT_MAJOR_VERSION = 11
-- CUDA_TOOLKIT_MINOR_VERSION = 0
-- Configuring done
-- Generating done
-- Build files have been written to: /content/COSMA/build
Scanning dependencies of target costa
Scanning dependencies of target Tiled-MM
Scanning dependencies of target gtest
[  1%] Building CXX object libs/gtest_mpi/external/gtest/CMakeFiles/gtest.dir/src/gtest-all.cpp.o
[  3%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/grid2D.cpp.o
[  4%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/block.cpp.o
[  6%] Building CXX object libs/Tiled-MM/src/Tiled-MM/CMakeFiles/Tiled-MM.dir/gpu_context.cpp.o
[  7%] Building CXX object libs/Tiled-MM/src/Tiled-MM/CMakeFiles/Tiled-MM.dir/mm_handle.cpp.o
[  9%] Building CXX object libs/Tiled-MM/src/Tiled-MM/CMakeFiles/Tiled-MM.dir/tile_dim.cpp.o
[ 10%] Building CXX object libs/Tiled-MM/src/Tiled-MM/CMakeFiles/Tiled-MM.dir/tiled_matrix.cpp.o
[ 12%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/interval.cpp.o
[ 13%] Building CXX object libs/Tiled-MM/src/Tiled-MM/CMakeFiles/Tiled-MM.dir/tiled_mm.cpp.o
[ 15%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/scalapack_layout.cpp.o
[ 16%] Building CXX object libs/Tiled-MM/src/Tiled-MM/CMakeFiles/Tiled-MM.dir/tile_coord.cpp.o
[ 18%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/communication_data.cpp.o
[ 20%] Linking CXX static library libTiled-MM.a
[ 20%] Built target Tiled-MM
[ 21%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/grid_cover.cpp.o
[ 23%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/ranks_reordering.cpp.o
[ 24%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/utils.cpp.o
[ 26%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/transform.cpp.o
[ 27%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/layout.cpp.o
[ 29%] Linking CXX static library libgtest.a
[ 29%] Built target gtest
Scanning dependencies of target main_gtest
Scanning dependencies of target main_gtest_mpi
[ 30%] Building CXX object tests/CMakeFiles/main_gtest.dir/main_gtest.cpp.o
[ 32%] Building CXX object tests/CMakeFiles/main_gtest_mpi.dir/main_gtest_mpi.cpp.o
[ 33%] Linking CXX static library libcosta.a
[ 33%] Built target costa
Scanning dependencies of target cosma
[ 35%] Building CXX object src/cosma/CMakeFiles/cosma.dir/blas.cpp.o
[ 36%] Building CXX object src/cosma/CMakeFiles/cosma.dir/buffer.cpp.o
[ 38%] Building CXX object src/cosma/CMakeFiles/cosma.dir/communicator.cpp.o
[ 38%] Built target main_gtest
[ 40%] Building CXX object src/cosma/CMakeFiles/cosma.dir/context.cpp.o
[ 40%] Built target main_gtest_mpi
[ 41%] Building CXX object src/cosma/CMakeFiles/cosma.dir/interval.cpp.o
[ 43%] Building CXX object src/cosma/CMakeFiles/cosma.dir/layout.cpp.o
[ 44%] Building CXX object src/cosma/CMakeFiles/cosma.dir/local_multiply.cpp.o
[ 46%] Building CXX object src/cosma/CMakeFiles/cosma.dir/mapper.cpp.o
[ 47%] Building CXX object src/cosma/CMakeFiles/cosma.dir/math_utils.cpp.o
[ 49%] Building CXX object src/cosma/CMakeFiles/cosma.dir/matrix.cpp.o
[ 50%] Building CXX object src/cosma/CMakeFiles/cosma.dir/memory_pool.cpp.o
[ 52%] Building CXX object src/cosma/CMakeFiles/cosma.dir/multiply.cpp.o
[ 53%] Building CXX object src/cosma/CMakeFiles/cosma.dir/one_sided_communicator.cpp.o
[ 55%] Building CXX object src/cosma/CMakeFiles/cosma.dir/strategy.cpp.o
[ 56%] Building CXX object src/cosma/CMakeFiles/cosma.dir/two_sided_communicator.cpp.o
[ 58%] Building CXX object src/cosma/CMakeFiles/cosma.dir/cinterface.cpp.o
[ 60%] Building CXX object src/cosma/CMakeFiles/cosma.dir/environment_variables.cpp.o
[ 61%] Building CXX object src/cosma/CMakeFiles/cosma.dir/pinned_buffers.cpp.o
[ 63%] Linking CXX static library libcosma.a
[ 63%] Built target cosma
Scanning dependencies of target test.scalar_matmul
Scanning dependencies of target test.mapper
Scanning dependencies of target test.multiply_using_layout
Scanning dependencies of target test.multiply
[ 64%] Building CXX object tests/CMakeFiles/test.mapper.dir/mapper.cpp.o
[ 66%] Building CXX object tests/CMakeFiles/test.multiply_using_layout.dir/multiply_using_layout.cpp.o
[ 67%] Building CXX object tests/CMakeFiles/test.scalar_matmul.dir/scalar_matmul.cpp.o
[ 69%] Building CXX object tests/CMakeFiles/test.multiply.dir/multiply.cpp.o
[ 70%] Linking CXX executable test.multiply_using_layout
/usr/bin/ld: cannot find -lCUDA_cublas_device_LIBRARY-NOTFOUND
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test.multiply_using_layout.dir/build.make:96: recipe for target 'tests/test.multiply_using_layout' failed
make[2]: *** [tests/test.multiply_using_layout] Error 1
CMakeFiles/Makefile2:509: recipe for target 'tests/CMakeFiles/test.multiply_using_layout.dir/all' failed
make[1]: *** [tests/CMakeFiles/test.multiply_using_layout.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 72%] Linking CXX executable test.mapper
/usr/bin/ld: cannot find -lCUDA_cublas_device_LIBRARY-NOTFOUND
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test.mapper.dir/build.make:96: recipe for target 'tests/test.mapper' failed
make[2]: *** [tests/test.mapper] Error 1
CMakeFiles/Makefile2:628: recipe for target 'tests/CMakeFiles/test.mapper.dir/all' failed
make[1]: *** [tests/CMakeFiles/test.mapper.dir/all] Error 2
[ 73%] Linking CXX executable test.scalar_matmul
/usr/bin/ld: cannot find -lCUDA_cublas_device_LIBRARY-NOTFOUND
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test.scalar_matmul.dir/build.make:96: recipe for target 'tests/test.scalar_matmul' failed
make[2]: *** [tests/test.scalar_matmul] Error 1
CMakeFiles/Makefile2:550: recipe for target 'tests/CMakeFiles/test.scalar_matmul.dir/all' failed
make[1]: *** [tests/CMakeFiles/test.scalar_matmul.dir/all] Error 2
[ 75%] Linking CXX executable test.multiply
/usr/bin/ld: cannot find -lCUDA_cublas_device_LIBRARY-NOTFOUND
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test.multiply.dir/build.make:96: recipe for target 'tests/test.multiply' failed
make[2]: *** [tests/test.multiply] Error 1
CMakeFiles/Makefile2:669: recipe for target 'tests/CMakeFiles/test.multiply.dir/all' failed
make[1]: *** [tests/CMakeFiles/test.multiply.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
[ 10%] Built target Tiled-MM
[ 27%] Built target costa
[ 56%] Built target cosma
[ 60%] Built target gtest
[ 61%] Built target main_gtest_mpi
[ 63%] Linking CXX executable test.multiply_using_layout
/usr/bin/ld: cannot find -lCUDA_cublas_device_LIBRARY-NOTFOUND
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test.multiply_using_layout.dir/build.make:96: recipe for target 'tests/test.multiply_using_layout' failed
make[2]: *** [tests/test.multiply_using_layout] Error 1
CMakeFiles/Makefile2:509: recipe for target 'tests/CMakeFiles/test.multiply_using_layout.dir/all' failed
make[1]: *** [tests/CMakeFiles/test.multiply_using_layout.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by kabicm** [comment]
Allright, this seems to be a bug in cmake versions < 3.12.2. So, the easiest option would be if you can upgrade your cmake.

Otherwise, I have added a [workaround](https://github.com/kabicm/Tiled-MM/blob/88b44a82447489f02c1ce744319d924ecd512852/CMakeLists.txt#L33) for this cmake bug that should fix it. Since the Tiled-MM submodule of COSMA is also updated, it would be best if you can do a fresh new
`git clone -recursive https://github.com/eth-cscs/COSMA`
and check if it fixes it for you.

**Comment by MQSchleich** [comment]
It installs like a charm! Thank you for resolving the issue.

**Comment by kabicm** [comment]
Great, thanks Manuel for your help! We've just released [COSMA-v2.5.1](https://github.com/eth-cscs/COSMA/releases/tag/v2.5.1) with this fix.
